### ISSUE TITLE
処理

### ISSUE THREAD

**Issue by saotomemao** [43zaki/ProjExD#23]
https://github.com/43zaki/ProjExD/blob/98bb27a9e976e6da2acd1f220ba789b6be832be5/ex06/shuting.py#L238

似た処理を繰り返しやっているのでループで回したら文章の量が削減できないでしょうか

**Comment by 43zaki** [comment]
引数を分かりやすい名前に指定しているため、for文にすると逆に見にくくなるため変更はしないです。
